
export const tableHeadCells = [
    "Azioni",
    "Numero preventivo",
    "Agenzia",
    "Cliente",
    "Stato",
    "Creato da",
    "Agente",
    "Data creazione",
    "Approva da",
    "Data approvazione",
    "Allegati",
];
export const tableData = [
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
    {
        Azioni: "vvvvvv",
        NumeroPreventivo: "PR-202200001",
        Agenzia: "Sogert s.p.a.",
        Cliente: "Comune di Napoli",
        Stato: "vvvvvv",
        CreatoDa: "Mario Rossi",
        Agente: "Mario Bianchi",
        DataCreazione: "23/03/2022",
        ApprovaDa: "23/03/2022",
        DataApprovazione: "",
        Allegati: "vvvvvv",
    },
];
